name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Safety
      id: safety
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Safety
        setup-command: mvn compile
        command: mvn test
        timeout: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAFETY_RESULTS: "${{steps.safety.outputs.result}}"
      with:
        runners: safety
